### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by fuchsmich** [black-sheep-dev/harbour-webview-example#1]
https://github.com/black-sheep-dev/harbour-webview-example/blob/472fd01dbcc3582c4e9b1fa9ecb3ab35dd6e02f1/rpm/harbour-webview.yaml#L34

should also require:
  - sailfish-components-webview-qt5
  - sailfish-components-webview-qt5-popups
  - sailfish-components-webview-qt5-pickers

**Comment by black-sheep-dev** [comment]
Thanks for the info. 
Added the dependencies to the yaml file.
